### ISSUE TITLE
Option to maximize from context menu

### ISSUE THREAD

**Issue by jplumeyssa** [deathau/maximise-active-pane-obsidian#13]
I have a friend who is starting to use Obsidian and he can't use shortcuts because of a disability. Would it be possible to add an option in the context menu (right-click) to open the file maximized and then another to restore?

**Comment by FelipeRearden** [comment]
Hello @jplumeyssa !!!

**I'm gonna try to help :)**

I suggest you take a look at these three plugins that lets you assign command palette commands to the Obsidian screen or mouse right-click:
- This way you can assign the `Maximize Acitve Pane: Toogle` to a button and use the mouse to click 

CMenu

https://github.com/chetachiezikeuzor/cMenu-Plugin


Customizable Sidebar

https://github.com/phibr0/obsidian-customizable-sidebar

Customizable Right Click Menu

https://github.com/kzhovn/obsidian-customizable-menu


I think the last one is what you are looking for :)

Have a great day!

**Comment by jplumeyssa** [comment]
Hi,

Thanks for this info! I think that last one is perfect. Thanks!

**Comment by FelipeRearden** [comment]
I'm glad to know that I helped you :)
