### ISSUE TITLE
Doesn't maximize with sliding-panes-obsidian 

### ISSUE THREAD

**Issue by gbrlb** [deathau/maximise-active-pane-obsidian#19]
In Obsidian v0.14.15, the maximise-active-pane-obsidian plugin doesn't work with the [sliding-panes-obsidian](https://github.com/deathau/sliding-panes-obsidian) plugin enabled.

**Comment by EhuddR** [comment]
Hi! Same problem here. 
Obsidian 0.14.15. 
OS: Arch Linux

**Comment by gbrlb** [comment]
It works again with the last update of [sliding-panes-obsidian](https://github.com/deathau/sliding-panes-obsidian).
