### ISSUE TITLE
Unmaximize oddity

### ISSUE THREAD

**Issue by DutchPete** [deathau/maximise-active-pane-obsidian#4]
After maximizing the panel in focus and working on it, I unmaximized. This is what I got:

<img width="1018" alt="max" src="https://user-images.githubusercontent.com/10794265/105000726-59ba1300-5a37-11eb-89d2-9a4499e5f5d9.png">

I had to correct it with a refresh - I presume that should not be necessary.

**Comment by deathau** [comment]
By the looks of the number of panes open, you are using this plug-in in conjunction with Sliding Panes, correct?
It looks like some sort of incompatibility there I'll need to sort out...

**Comment by DutchPete** [comment]
Yes, I do use it in conjunction with Sliding Panes.

**Comment by DutchPete** [comment]
Have you had a chance to look at this?

**Comment by deathau** [comment]
I'm sorry, I haven't had a chance yet

**Comment by pjeby** [comment]
I just submitted a PR (#7) to fix this, so now you don't have to.  :wink:

**Comment by deathau** [comment]
Thanks so much for this @pjeby!

**Comment by DutchPete** [comment]
@pjeby : many thanks for this fix. One thing I notice is if I have say 5 notes open, and working on no. 3 in maximized mode, when I unmaximize all the panes are shoved to the side and no.1 is in focus. Would it be possible that the unmaximizing sets the original pane back in focus, i.e. no.3 in my example?

**Comment by pjeby** [comment]
I think you need to update your version of Obsidian and/or the Sliding Panes plugin; the older versions used to do what you describe, but the current ones don't, at least for me.

What happens in mine is that initially, the first pane is scrolled out, then it scrolls to the third (or whatever) pane, and it's still active.  But there is a slight delay where only the first pane is visible, then it scrolls to where it should be and all is well.

**Comment by DutchPete** [comment]
@pjeby: I am using Obs 0.10.11 and SP 3.2.2, and AFAIK there are no newer versions of either.

**Comment by pjeby** [comment]
And I assume you're also using the new version of *this* plugin?  Other than that, I have no idea why it works for me.

**Comment by DutchPete** [comment]
It IS working now. Since my last comment I refreshed the vault a few times for other reasons, so it is likely that that did the trick. My apologies and again a big thank you for fixing this issue.
